### ISSUE TITLE
svg loader re-arranges internal elements

### ISSUE THREAD

**Issue by kmcmichael-twist** [jhamlet/svg-react-loader#38] opened 2016-09-20 12:02 UTC
I'm having a problem with the loader re-ordering the elements in the SVG and, because z-index is implied by order, this is breaking my svg images. I have found a work-around but I shouldn't need to edit my svg to get the loader to work properly.

Original svg:
`
<?xml version="1.0"?>
<svg viewBox="0 0 170 228" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <g display="inline">
  <path stroke="#000000" id="svg_7" d="m136.590914,33.681802l0,134.495052l-62.000002,0l0,-134.495052" transform="rotate(-180 105.59091186523438,100.92932891845703) " stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" fill="#ffffff"/>
  <polygon id="svg_6" fill="none"/>
  <rect fill="#000000" stroke="#000000" stroke-width="5" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x="100" y="17.54546" width="0" height="1" id="svg_12"/>
  <rect stroke="#000000" fill="#000000" stroke-width="5" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x="76" y="47.18181" width="45" height="134" id="svg_13" transform="rotate(-180 98.5,114.18180847167969) "/>
  <line stroke="#000000" id="svg_1" y2="35.24558" x2="135.906533" y1="48.181816" x1="120" stroke-width="2" fill="none"/>
  <polyline stroke="#000000" id="svg_3" fill="none" stroke-width="2" points="122.5083999633789,183.04354706658705 129.70687866210938,175.23901291317634 136.9053497314453,167.43447875976562 "/>
  <path stroke="#000000" transform="rotate(100.27760314941406 125.11046600341797,107.50355529785155) " fill="#ffffff" stroke-width="3" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" d="m90.187333,107.415397l34.923135,-36.644l34.923135,36.644l-17.461572,0l0,36.820321l-34.923135,0l0,-36.820321l-17.461572,0l0.000009,0z" id="svg_14"/>
  <path stroke="#000000" fill="#ffffff" stroke-width="4" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" d="m84,208.363634l-50.271428,-38.971429l-0.728571,-114.820786l50.271428,-38.407787l0,153.228573l0.728571,38.971429z" id="svg_9"/>
  <path stroke="#000000" fill="none" stroke-width="5" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" id="svg_29" d="m74.207063,92.994622c-0.791711,0.042678 -1.472067,0.030768 -1.894889,0.485966c-0.513212,0.552505 -0.838472,1.232362 -1.16167,1.918588c-0.331671,0.704229 -0.418587,1.443236 -0.57768,2.169467c-0.179531,0.819511 -0.335009,1.639232 -0.386137,2.362081c-0.058061,0.820712 -0.139966,1.590923 -0.182572,2.279498c-0.055065,0.889846 -0.052272,1.652415 -0.144705,2.497702c-0.071833,0.656851 -0.102738,1.486471 -0.145216,2.226967c-0.046673,0.813599 -0.005534,1.638574 0.023232,2.427209c0.028681,0.786335 0.0573,1.570954 0.086744,2.37818c0.025476,0.698443 0.053995,1.480337 0.086419,2.369269c0.02659,0.728997 0.053652,1.546902 0.147904,2.264672c0.109673,0.835244 0.233732,1.580034 0.318247,2.318543c0.101816,0.88974 0.133052,1.60377 0.245719,2.412122c0.098985,0.710173 0.248663,1.571685 0.546908,2.259582c0.284351,0.655861 0.823647,1.089418 1.358176,1.544413c0.520349,0.442931 1.07536,0.771281 1.649506,0.937649l0.650143,-0.035047"/>
 </g>
</svg>`

This file loads into my react app with the ordering of the elements changed (and thus some background elements move to the foreground). If I wrap the last three path elements in a <g> tag, the ordering is preserved after load - but needing to arbitrarily edit the svg is a huge problem...

**Comment by jhamlet** [comment] 2016-09-20 12:37
@kmcmichael-twist This is a duplicate of #26 and has been fixed in the v0.4.0 branch.

You can try the latest by `npm install svg-react-loader@next` to see if your problem goes away (if it doesn't please reopen this issue).

I haven't released v0.4.0 as latest yet because I haven't had the time to generate sufficient test coverage.

**Closed by jhamlet** 2016-09-20 12:37 UTC
Labels: bug, duplicate
